export const EDGE_FUNCTIONS = [
  'chat',
  'match',
  'simulate',
  'analyze-diary',
  'analyze-self-discovery',
  'create-diary-entry',
  'finalize-diary-entry',
  'diary-audio-url',
  'delete-diary-entry',
  'delete-diary-audio',
  'export-diary',
  'retry-diary-entry',
  'update-diary-transcript',
  'save-profile',
  'card-game-catalog',
  'card-game-session',
  'card-game-result',
  'get-profile',
  'profile-privacy',
  'list-conversations',
  'list-diary',
  'diary-summary',
  'community',
  'lab-choices',
  'persona',
  'merge-anonymous',
  'delete-account',
] as const

export type EdgeFunctionName = (typeof EDGE_FUNCTIONS)[number]
